### PR TITLE
Create AIArena page.

### PR DESCRIPTION
**Pull request by glipR**
Here is a preview of the page:
image

Also adds a link to the main page of the blog.

### CODE REVIEW

**Comment by glipR** [comment]
@Ali-Toosi if you are happy with this will merge.

**Comment by glipR** [comment]
Going to wait on Amin's response before merging since this will be public.

**Comment by Ali-Toosi** [comment]
Sounds good. Let's not forget to update the date to whatever date we decide as well. Options are Thursday/Friday/Saturday of midsem break week.

**Comment by glipR** [comment]
image
image
Here's the two affected pages as of latest pages.

@Ali-Toosi can you give one last readthrough to make sure the info is correct?

**Comment by glipR** [comment]
Also @eggeek I don't have write access and so can't merge this PR myself. Would you be able to give me/Ali access or merge this for us?
Cheers.

**Comment by eggeek** [comment]
> Also @eggeek I don't have write access and so can't merge this PR myself. Would you be able to give me/Ali access or merge this for us?
> Cheers.

Sure, no problem.

**Comment by Ali-Toosi** [comment]
looks (looked) good to me :D

**Comment by eggeek** [comment]
Is this an ICPC-style contest with interactive problems? 
If not, please write somewhere explicitly; otherwise, some highly motivated participants might go through all our beginner tutorials in other tabs and finally realize they are not helpful...

**Comment by glipR** [comment]
Fair point, will make another PR.

**Pull request merged**
